In [11]:
# Import librairies

import pandas as pd

In [12]:
pd.set_option("display.max_columns", None)

# APL dataset

- Dataset with APL indicator per municipalities, 
  source : https://drees.shinyapps.io/carto-apl/

In [13]:
# URL of the CSV file of APL data
apl_url = 'https://medical-deserts-project.s3.eu-north-1.amazonaws.com/APL_mg_2016.csv'

# Read the CSV file from the URL into a DataFrame
apl_df = pd.read_csv(apl_url, sep = ';', encoding='utf-8')

In [14]:
# Dataset customization

# Change columns name
apl_df = apl_df.rename(columns={'Libellé de la commune': 'Ville'})

# Focus on metropolitan France
apl_df = apl_df[~apl_df['Code commune'].str.startswith(('97', '98'))]

# Transform APL columns in float type
apl_df["APL aux médecins généralistes (sans borne d'âge)"] = apl_df["APL aux médecins généralistes (sans borne d'âge)"].str.replace(',', '.').astype(float)
apl_df["APL aux médecins généralistes de 65 ans et moins"] = apl_df["APL aux médecins généralistes de 65 ans et moins"].str.replace(',', '.').astype(float)
apl_df["APL aux médecins généralistes de 62 ans et moins"] = apl_df["APL aux médecins généralistes de 62 ans et moins"].str.replace(',', '.').astype(float)

# Replace null values by median value in APL columns
apl_df["APL aux médecins généralistes (sans borne d'âge)"] = apl_df["APL aux médecins généralistes (sans borne d'âge)"].fillna(apl_df["APL aux médecins généralistes (sans borne d'âge)"].median())
apl_df["APL aux médecins généralistes de 65 ans et moins"] = apl_df["APL aux médecins généralistes de 65 ans et moins"].fillna(apl_df["APL aux médecins généralistes de 65 ans et moins"].median())
apl_df["APL aux médecins généralistes de 62 ans et moins"] = apl_df["APL aux médecins généralistes de 62 ans et moins"].fillna(apl_df["APL aux médecins généralistes de 65 ans et moins"].median())

In [15]:
print('Number of rows :', apl_df.shape[0])
print('Number of columns :', apl_df.shape[1])
print()

# Show first rows of the dataset
print('First rows of the dataset :')
display(apl_df.head())
print()

# Dataset statistics
print('Basics statistics :')
summary_stats_all = apl_df.describe(include='all')
display(summary_stats_all)
print()

# Missing values percentage
missing_percentages = (apl_df.isna().mean() * 100).round(2)
print('Percentage of missing values: ')
print(missing_percentages)

Number of rows : 35798
Number of columns : 7

First rows of the dataset :

,Code commune,Ville,Population totale,APL aux médecins généralistes (sans borne d'âge),APL aux médecins généralistes de 65 ans et moins,APL aux médecins généralistes de 62 ans et moins,Population standardisée par la consommation de soins par tranche d'âge
0,01001,L'Abergement-Clémenciat,767.0,2.293,2.010,1.546,"765,296"
1,01002,L'Abergement-de-Varey,239.0,2.600,2.511,2.384,"239,164"
2,01004,Ambérieu-en-Bugey,14022.0,4.079,3.976,3.558,"13806,292"
3,01005,Ambérieux-en-Dombes,1627.0,4.378,4.378,3.782,"1597,628"
4,01006,Ambléon,109.0,1.069,0.920,0.920,"114,565"

Basics statistics :

,Code commune,Ville,Population totale,APL aux médecins généralistes (sans borne d'âge),APL aux médecins généralistes de 65 ans et moins,APL aux médecins généralistes de 62 ans et moins,Population standardisée par la consommation de soins par tranche d'âge
count,35798,35753,35792.000000,35798.000000,35798.000000,35798.000000,35792
unique,35798,33360,NaN,NaN,NaN,NaN,35318
top,01001,Sainte-Colombe,NaN,NaN,NaN,NaN,"156,174"
freq,1,13,NaN,NaN,NaN,NaN,4
mean,NaN,NaN,1788.890199,3.269597,3.000157,2.627924,NaN
std,NaN,NaN,8252.853730,1.277951,1.202274,1.115096,NaN
min,NaN,NaN,1.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,NaN,197.000000,2.487250,2.253000,1.931000,NaN
50%,NaN,NaN,443.000000,3.209000,2.942500,2.574000,NaN
75%,NaN,NaN,1104.000000,3.985750,3.686000,3.266000,NaN
max,NaN,NaN,466297.000000,19.685000,12.885000,12.885000,NaN

Percentage of missing values:
Code commune                                                              0.00
Ville                                                                     0.13
Population totale                                                         0.02
APL aux médecins généralistes (sans borne d'âge)                          0.00
APL aux médecins généralistes de 65 ans et moins                          0.00
APL aux médecins généralistes de 62 ans et moins                          0.00
Population standardisée par la consommation de soins par tranche d'âge    0.02
dtype: float64

# Geographical coordinates dataset

- Dataset with geographical coordinates per municipalities,
  source : https://www.data.gouv.fr/fr/datasets/villes-de-france/

In [16]:
# URL of the CSV file of cities data
cities_url = 'https://medical-deserts-project.s3.eu-north-1.amazonaws.com/cities.csv'

# Read the CSV file from the URL into a DataFrame
cities_df = pd.read_csv(cities_url)

In [17]:
# Dataset customization

# Change columns name
cities_df = cities_df.rename(columns={'city_code': 'Ville', 'insee_code': 'Code commune'})

# Focus on metropolitan France
cities_df = cities_df[~cities_df['Code commune'].str.startswith(('97', '98'))]

In [18]:
print('Number of rows :', cities_df.shape[0])
print('Number of columns :', cities_df.shape[1])
print()

# Show first rows of the dataset
print('First rows of the dataset :')
display(cities_df.head())
print()

# Dataset statistics
print('Basics statistics :')
summary_stats_all = cities_df.describe(include='all')
display(summary_stats_all)
print()

# Missing values percentage
missing_percentages = (cities_df.isna().mean() * 100).round(2)
print('Percentage of missing values: ')
print(missing_percentages)

Number of rows : 38717
Number of columns : 10

First rows of the dataset :

,Code commune,Ville,zip_code,label,latitude,longitude,department_name,department_number,region_name,region_geojson_name
0,25620,ville du pont,25650,ville du pont,46.999873,6.498147,doubs,25,bourgogne-franche-comté,Bourgogne-Franche-Comté
1,25624,villers grelot,25640,villers grelot,47.361512,6.235167,doubs,25,bourgogne-franche-comté,Bourgogne-Franche-Comté
2,25615,villars les blamont,25310,villars les blamont,47.368384,6.871415,doubs,25,bourgogne-franche-comté,Bourgogne-Franche-Comté
3,25619,les villedieu,25240,les villedieu,46.713906,6.265831,doubs,25,bourgogne-franche-comté,Bourgogne-Franche-Comté
4,25622,villers buzon,25170,villers buzon,47.228558,5.852187,doubs,25,bourgogne-franche-comté,Bourgogne-Franche-Comté

Basics statistics :

,Code commune,Ville,zip_code,label,latitude,longitude,department_name,department_number,region_name,region_geojson_name
count,38717,38717,38717.000000,38717,38717.000000,38717.000000,38717,38717,38717,38717
unique,34868,32579,NaN,32560,NaN,NaN,96,96,13,13
top,14654,livarot pays d auge,NaN,marseille,NaN,NaN,pas-de-calais,62,grand est,Grand Est
freq,22,22,NaN,27,NaN,NaN,915,915,5674,5674
mean,NaN,NaN,46175.516698,NaN,46.972916,2.777771,NaN,NaN,NaN,NaN
std,NaN,NaN,25421.524971,NaN,2.208628,2.688881,NaN,NaN,NaN,NaN
min,NaN,NaN,1000.000000,NaN,41.435023,-5.086014,NaN,NaN,NaN,NaN
25%,NaN,NaN,24530.000000,NaN,45.176588,0.675359,NaN,NaN,NaN,NaN
50%,NaN,NaN,48400.000000,NaN,47.399768,2.686532,NaN,NaN,NaN,NaN
75%,NaN,NaN,66800.000000,NaN,48.828093,4.963732,NaN,NaN,NaN,NaN
max,NaN,NaN,95880.000000,NaN,51.072906,9.529052,NaN,NaN,NaN,NaN

Percentage of missing values:
Code commune           0.0
Ville                  0.0
zip_code               0.0
label                  0.0
latitude               0.0
longitude              0.0
department_name        0.0
department_number      0.0
region_name            0.0
region_geojson_name    0.0
dtype: float64

# INSEE dataset

- Dataset with INSEE information per municipalities, 
source : https://www.data.gouv.fr/fr/datasets/data-insee-sur-les-communes/

In [19]:
# URL of the CSV file of INSEE data
insee_url = 'https://medical-deserts-project.s3.eu-north-1.amazonaws.com/MDB-INSEE-V2.csv'

# Read the CSV file from the URL into a DataFrame
insee_df = pd.read_csv(insee_url, sep = ';', encoding='utf-8')

C:\Users\alexa\AppData\Local\Temp\ipykernel_4048\2625714540.py:5: DtypeWarning: Columns (0,15,100) have mixed types. Specify dtype option on import or set low_memory=False.
  insee_df = pd.read_csv(insee_url, sep = ';', encoding='utf-8')

In [20]:
# Dataset customization

# Change columns name
insee_df = insee_df.rename(columns={'LIBGEO': 'Ville', 'CODGEO': 'Code commune'})

# Convert the 'Code commune' column to strings
insee_df['Code commune'] = insee_df['Code commune'].astype(str)

# Focus on metropolitan France
insee_df = insee_df[~insee_df['Code commune'].str.startswith(('97', '98'))]

# Add a zero if "Code commune" has only 4 characters
insee_df['Code commune'] = insee_df['Code commune'].apply(lambda x: '0' + x if len(x) == 4 else x)

# Add APL data from apl_df
insee_df = insee_df.merge(apl_df[["Code commune", "APL aux médecins généralistes (sans borne d'âge)"]], on="Code commune", how="left")
insee_df = insee_df.merge(apl_df[["Code commune", "APL aux médecins généralistes de 65 ans et moins"]], on="Code commune", how="left")
insee_df = insee_df.merge(apl_df[["Code commune", "APL aux médecins généralistes de 62 ans et moins"]], on="Code commune", how="left")

# Add geographical coordonates from cities_df
insee_df = insee_df.merge(cities_df[["Code commune", "latitude"]], on="Code commune", how="left")
insee_df = insee_df.merge(cities_df[["Code commune", "longitude"]], on="Code commune", how="left")

# Remove useless columns
insee_df = insee_df.drop([
    "Code commune", 
    "Nb Pharmacies et parfumerie", 
    "Orientation Economique",
    "Indice Evasion Client",
    "Score Evasion Client", 
    "Score Synergie Médicale",
    "Ville", 
    "REG", 
    "DEP", 
    "Score Démographique", 
    "Score Ménages", 
    "Urbanité Ruralité",
    "Capacité Fiscale", 
    "Taux Evasion Client",
    "SEG Environnement Démographique Obsolète", 
    "SYN MEDICAL", 
    "CP"
    ], 
    axis=1)

# Remove useless columns - Departemental or regional datas
insee_df = insee_df.drop([
    "Indice Fiscal Partiel", # Duplicate with "Moyenne Revenus Fiscaux Régionaux"
    "Score Fiscal", # Duplicate with "Moyenne Revenus Fiscaux Régionaux"
    #"Moyenne Revenus Fiscaux Départementaux", 
    #"Moyenne Revenus Fiscaux Régionaux", 
    #"Dep Moyenne Salaires Horaires", 
    #"Dep Moyenne Salaires Cadre Horaires", 
    #"Dep Moyenne Salaires Prof Intermédiaire Horaires", 
    #"Dep Moyenne Salaires Employé Horaires", 
    #"Dep Moyenne Salaires Ouvrié Horaires", 
    #"Reg Moyenne Salaires Horaires", 
    #"Reg Moyenne Salaires Cadre Horaires", 
    #"Reg Moyenne Salaires Prof Intermédiaire Horaires", 
    #"Reg Moyenne Salaires Employé Horaires", 
    #"Reg Moyenne Salaires Ouvrié Horaires", 
    #"Valeur ajoutée régionale", 
    #"Moyenne Revnus fiscaux", 
    #"Nb Industries des biens intermédiaires", 
    #"Nb de Commerce", 
    #"Nb de Services aux particuliers", 
    #"Nb institution de Education, santé, action sociale, administration", 
    #"PIB Régionnal", 
    "Score VA Région", # Indice VA already in the dataframe
    "Score PIB"#,  # Indice PIB already in the dataframe
    #"Seg Cap Fiscale",
    ], 
    axis=1)

# Remove useless columns - Departemental or regional datas
insee_df = insee_df.drop([
    "Population", 
    "Evolution Population", 
    "Evolution Pop %", 
    "Nb Femme", 
    "Nb Homme", 
    "Nb Mineurs", 
    "Nb Majeurs", 
    "Nb Etudiants", 
    "Taux étudiants",
    "Score Croissance Population"
    ], 
    axis=1)

# Transform Object column in numeric column
insee_df["Indice Synergie Médicale"] = insee_df["Indice Synergie Médicale"].str.replace(',', '.').astype(float)
insee_df["Densité Médicale BV"] = insee_df["Densité Médicale BV"].str.replace(',', '.').astype(float)
insee_df["Indice Démographique"] = insee_df["Indice Démographique"].str.replace(',', '.').astype(float)
insee_df["Indice Ménages"] = insee_df["Indice Ménages"].str.replace(',', '.').astype(float)
insee_df["Dep Moyenne Salaires Horaires"] = insee_df["Dep Moyenne Salaires Horaires"].str.replace(',', '.').astype(float)
insee_df["Dep Moyenne Salaires Cadre Horaires"] = insee_df["Dep Moyenne Salaires Cadre Horaires"].str.replace(',', '.').astype(float)
insee_df["Dep Moyenne Salaires Prof Intermédiaire Horaires"] = insee_df["Dep Moyenne Salaires Prof Intermédiaire Horaires"].str.replace(',', '.').astype(float)
insee_df["Dep Moyenne Salaires Employé Horaires"] = insee_df["Dep Moyenne Salaires Employé Horaires"].str.replace(',', '.').astype(float)
insee_df["Dep Moyenne Salaires Ouvrié Horaires"] = insee_df["Dep Moyenne Salaires Ouvrié Horaires"].str.replace(',', '.').astype(float)
insee_df["Reg Moyenne Salaires Horaires"] = insee_df["Reg Moyenne Salaires Horaires"].str.replace(',', '.').astype(float)
insee_df["Reg Moyenne Salaires Cadre Horaires"] = insee_df["Reg Moyenne Salaires Cadre Horaires"].str.replace(',', '.').astype(float)
insee_df["Reg Moyenne Salaires Prof Intermédiaire Horaires"] = insee_df["Reg Moyenne Salaires Prof Intermédiaire Horaires"].str.replace(',', '.').astype(float)
insee_df["Reg Moyenne Salaires Employé Horaires"] = insee_df["Reg Moyenne Salaires Employé Horaires"].str.replace(',', '.').astype(float)
insee_df["Reg Moyenne Salaires Ouvrié Horaires"] = insee_df["Reg Moyenne Salaires Ouvrié Horaires"].str.replace(',', '.').astype(float)
insee_df["Valeur ajoutée régionale"] = insee_df["Valeur ajoutée régionale"].str.replace(',', '.').astype(float)
insee_df["Score Urbanité"] = insee_df["Score Urbanité"].str.replace(',', '.').astype(float)
insee_df["Moyenne Revnus fiscaux"] = insee_df["Moyenne Revnus fiscaux"].str.replace(',', '.').astype(float)
insee_df["Score Croissance Entrepreneuriale"] = insee_df["Score Croissance Entrepreneuriale"].str.replace(',', '.').astype(float)

# Remove rows with missing values in the "longitude" and "latitude" columns
#insee_df.dropna(subset=['longitude', 'latitude'], inplace=True)
insee_df = insee_df.dropna()

In [21]:
print('Number of rows :', insee_df.shape[0])
print('Number of columns :', insee_df.shape[1])
print()

# Show first rows of the dataset
print('First rows of the dataset :')
display(insee_df.head())
print()

# Dataset statistics
print('Basics statistics :')
summary_stats_all = insee_df.describe(include='all')
display(summary_stats_all)
print()

# Missing values percentage
missing_percentages = (insee_df.isna().mean() * 100).round(2)
print('Percentage of missing values: ')
print(missing_percentages)

Number of rows : 56414
Number of columns : 75

First rows of the dataset :

,Dynamique Entrepreneuriale,Dynamique Entrepreneuriale Service et Commerce,Synergie Médicale COMMUNE,Indice Synergie Médicale,SEG Croissance POP,Nb Omnipraticiens BV,Nb Infirmiers Libéraux BV,Nb dentistes Libéraux BV,Nb pharmaciens Libéraux BV,Densité Médicale BV,Score équipement de santé BV,Indice Démographique,Indice Ménages,Nb Ménages,Nb Résidences Principales,Nb propriétaire,Nb Logement,Nb Résidences Secondaires,Nb Log Vacants,Nb Occupants Résidence Principale,Nb Entreprises Secteur Services,Nb Entreprises Secteur Commerce,Nb Entreprises Secteur Construction,Nb Entreprises Secteur Industrie,Nb Création Enteprises,Nb Création Industrielles,Nb Création Construction,Nb Création Commerces,Nb Création Services,Moyenne Revenus Fiscaux Départementaux,Moyenne Revenus Fiscaux Régionaux,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Dep Moyenne Salaires Ouvrié Horaires,Reg Moyenne Salaires Horaires,Reg Moyenne Salaires Cadre Horaires,Reg Moyenne Salaires Prof Intermédiaire Horaires,Reg Moyenne Salaires Employé Horaires,Reg Moyenne Salaires Ouvrié Horaires,Valeur ajoutée régionale,Score Urbanité,Nb Atifs,Nb Actifs Salariés,Nb Actifs Non Salariés,Nb Logement Secondaire et Occasionnel,Nb Hotel,Capacité Hotel,Nb Camping,Capacité Camping,Dynamique Démographique BV,Taux Propriété,Dynamique Démographique INSEE,Capacité Fisc,Moyenne Revnus fiscaux,"Nb Education, santé, action sociale",Nb Services personnels et domestiques,"Nb Santé, action sociale",Nb Industries des biens intermédiaires,Nb de Commerce,Nb de Services aux particuliers,"Nb institution de Education, santé, action sociale, administration",PIB Régionnal,Score Croissance Entrepreneuriale,Environnement Démographique,Fidélité,Seg Cap Fiscale,Seg Dyn Entre,DYN SetC,APL aux médecins généralistes (sans borne d'âge),APL aux médecins généralistes de 65 ans et moins,APL aux médecins généralistes de 62 ans et moins,latitude,longitude
0,57.0,23.0,114,114.56713,en croissance démographique,9,14,7,7,0.092860,4,44.19769,37.22029,247,248,196,289,32,9,728,7.0,11.0,2.0,2.0,4.0,0.0,2.0,1.0,1.0,12509,10458,11.410345,21.963793,12.558621,8.743103,9.268966,11.873022,21.78783,12.704057,8.783164,9.30142,86957.45836,0.0,295.0,254.0,41.0,32.0,0.0,0.0,0.0,0.0,1.Accroissement par excédent naturel et migrat...,67,-1,117,11483.5,3.0,1.0,0.0,9364,9350,3372,15105,173681,0.01585,Bassin Industriel en croissance démographique,Pop Sédentaire,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,2.293,2.010,1.546,46.153721,4.925850
1,45.0,4.0,143,143.71141,en croissance démographique,31,36,18,18,0.099229,4,10.18071,10.09619,67,67,61,142,71,4,168,4.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,12509,10458,11.410345,21.963793,12.558621,8.743103,9.268966,11.873022,21.78783,12.704057,8.783164,9.30142,86957.45836,0.0,57.0,49.0,8.0,71.0,0.0,0.0,0.0,0.0,1.Accroissement par excédent naturel et migrat...,42,0,110,11483.5,0.0,0.0,0.0,9364,9350,3372,15105,173681,0.00173,Bassin Résidentiel en croissance démographique,Pop Sédentaire,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,2.600,2.511,2.384,46.009606,5.428088
2,634.0,828.0,366,367.82080,en croissance démographique,31,36,18,18,0.099229,4,696.92134,699.19896,4640,4635,1968,5184,135,414,11015,342.0,301.0,58.0,108.0,83.0,4.0,14.0,27.0,38.0,12509,10458,11.410345,21.963793,12.558621,8.743103,9.268966,11.873022,21.78783,12.704057,8.783164,9.30142,86957.45836,37.5,4556.0,4203.0,353.0,135.0,2.0,52.0,0.0,0.0,1.Accroissement par excédent naturel et migrat...,37,-55,250,11483.5,113.0,41.0,118.0,9364,9350,3372,15105,173681,0.38471,Bassin Résidentiel en croissance démographique,Pop Mobile,Fiscalité moyenne,Dynamique Economique,Bonne Dynamique Entreprise Serv et Com,4.079,3.976,3.558,45.961049,5.372275
3,113.0,62.0,132,132.65668,en croissance démographique,12,12,6,6,1.000000,1,85.77400,71.27610,473,473,344,505,14,18,1406,22.0,26.0,17.0,10.0,6.0,0.0,4.0,2.0,0.0,12509,10458,11.410345,21.963793,12.558621,8.743103,9.268966,11.873022,21.78783,12.704057,8.783164,9.30142,86957.45836,0.0,621.0,535.0,86.0,14.0,2.0,17.0,1.0,72.0,Grande Ville,68,-3,127,11483.5,5.0,2.0,7.0,9364,9350,3372,15105,173681,0.02824,Bassin Urbain en croissance démographique,Pop Mobile,Fiscalité moyenne,Moyenne dynamique,Faible Dynamique Serv et Com,4.378,4.378,3.782,45.996164,4.911967
4,42.0,1.0,121,121.60196,en croissance démographique,26,21,10,10,0.100905,3,5.24276,6.17827,41,41,28,57,13,3,86,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12509,10458,11.410345,21.963793,12.558621,8.743103,9.268966,11.873022,21.78783,12.704057,8.783164,9.30142,86957.45836,0.0,37.0,33.0,4.0,13.0,0.0,0.0,0.0,0.0,3.Accroissement par excédent migratoire,49,0,109,11483.5,0.0,0.0,0.0,9364,9350,3372,15105,173681,0.00000,Bassin Résidentiel en croissance démographique,Pop Sédentaire,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,1.069,0.920,0.920,45.749886,5.594585

Basics statistics :

,Dynamique Entrepreneuriale,Dynamique Entrepreneuriale Service et Commerce,Synergie Médicale COMMUNE,Indice Synergie Médicale,SEG Croissance POP,Nb Omnipraticiens BV,Nb Infirmiers Libéraux BV,Nb dentistes Libéraux BV,Nb pharmaciens Libéraux BV,Densité Médicale BV,Score équipement de santé BV,Indice Démographique,Indice Ménages,Nb Ménages,Nb Résidences Principales,Nb propriétaire,Nb Logement,Nb Résidences Secondaires,Nb Log Vacants,Nb Occupants Résidence Principale,Nb Entreprises Secteur Services,Nb Entreprises Secteur Commerce,Nb Entreprises Secteur Construction,Nb Entreprises Secteur Industrie,Nb Création Enteprises,Nb Création Industrielles,Nb Création Construction,Nb Création Commerces,Nb Création Services,Moyenne Revenus Fiscaux Départementaux,Moyenne Revenus Fiscaux Régionaux,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Dep Moyenne Salaires Ouvrié Horaires,Reg Moyenne Salaires Horaires,Reg Moyenne Salaires Cadre Horaires,Reg Moyenne Salaires Prof Intermédiaire Horaires,Reg Moyenne Salaires Employé Horaires,Reg Moyenne Salaires Ouvrié Horaires,Valeur ajoutée régionale,Score Urbanité,Nb Atifs,Nb Actifs Salariés,Nb Actifs Non Salariés,Nb Logement Secondaire et Occasionnel,Nb Hotel,Capacité Hotel,Nb Camping,Capacité Camping,Dynamique Démographique BV,Taux Propriété,Dynamique Démographique INSEE,Capacité Fisc,Moyenne Revnus fiscaux,"Nb Education, santé, action sociale",Nb Services personnels et domestiques,"Nb Santé, action sociale",Nb Industries des biens intermédiaires,Nb de Commerce,Nb de Services aux particuliers,"Nb institution de Education, santé, action sociale, administration",PIB Régionnal,Score Croissance Entrepreneuriale,Environnement Démographique,Fidélité,Seg Cap Fiscale,Seg Dyn Entre,DYN SetC,APL aux médecins généralistes (sans borne d'âge),APL aux médecins généralistes de 65 ans et moins,APL aux médecins généralistes de 62 ans et moins,latitude,longitude
count,56414.000000,56414.000000,56414.000000,56414.000000,56414,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000,56414,56414,56414,56414,56414,56414.000000,56414.000000,56414.000000,56414.000000,56414.000000
unique,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2,3,3,3,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,en croissance démographique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.Accroissement par excédent naturel et migrat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bassin Résidentiel en croissance démographique,Pop Sédentaire,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,56403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24469,39034,45583,38559,40619,NaN,NaN,NaN,NaN,NaN
mean,216.745418,272.814160,137.004485,137.686064,NaN,16.209115,16.001773,7.682526,7.682526,0.295712,2.482540,235.310856,251.918337,1671.771759,1670.903109,771.666466,2017.115787,190.032067,156.180611,3748.673149,111.375705,100.700287,22.108147,33.589074,22.799110,1.309888,3.515528,5.857589,12.116106,10280.434431,10277.336831,10.950882,21.177406,12.432828,8.657549,9.025651,11.107464,21.243917,12.491197,8.674310,9.091158,39521.368119,9.841972,1453.670490,1282.537367,171.133123,189.972915,1.368472,49.083969,0.444411,56.299305,NaN,54.760715,-12.985465,-162.330237,10278.885631,31.068050,9.676056,32.882636,3076.023682,4394.087797,1750.693409,7709.059932,77285.037508,0.091750,NaN,NaN,NaN,NaN,NaN,3.298298,3.031462,2.660037,47.170504,2.417447
std,1117.781938,1677.843823,391.520197,393.467959,NaN,12.676738,13.825494,6.649198,6.649198,0.374648,1.351979,1194.698314,1417.386223,9406.009473,9382.116483,3457.660713,11030.927228,1035.311247,1143.563665,18953.778830,682.268969,624.932096,110.637545,175.109517,148.197901,6.413732,25.108467,34.823288,83.567181,1446.303459,1047.850879,0.890082,0.761982,0.372253,0.223183,0.389000,0.708977,0.563711,0.301954,0.188340,0.290390,42293.560290,22.302730,7159.961433,6421.173476,761.800175,1035.229491,7.087131,358.020421,1.702821,341.035870,NaN,15.636947,98.729832,4311.928580,982.956700,200.396811,54.006450,200.734714,2504.476974,4621.622988,3062.186653,6464.621770,82070.981224,0.565837,NaN,NaN,NaN,NaN,NaN,1.238916,1.163633,1.073509,2.112188,2.791610
min,1.000000,1.000000,13.000000,13.064670,NaN,1.000000,0.000000,0.000000,0.000000,0.032518,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6282.000000,7748.000000,9.862500,19.750000,11.740000,8.261905,8.300000,10.574510,20.509549,12.175380,8.453394,8.725000,3021.411002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,-1929.000000,-140594.000000,7664.000000,0.000000,0.000000,0.000000,30.000000,342.000000,187.000000,828.000000,6358.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,41.435023,-5.086014
25%,23.000000,7.000000,56.000000,56.278590,NaN,8.000000,8.000000,3.000000,3.000000,0.082132,1.000000,15.667320,15.068940,100.000000,100.000000,77.000000,137.000000,13.000000,8.000000,255.000000,4.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,9570.000000,9929.000000,10.400000,20.655714,12.160000,8.532468,8.760000,10.653774,21.013953,12.253774,8.569608,8.848889,19749.437990,0.000000,100.000000,75.000000,21.000000,13.000000,0.000000,0.000000,0.000000,0.000000,NaN,45.000000,-3.000000,73.000000,9750.500000,0.000000,0.000000,0.000000,1393.000000,2050.000000,779.000000,4162.000000,35310.000000,0.001730,NaN,NaN,NaN,NaN,NaN,2.539000,2.320000,1.991000,45.566135,0.050955
50%,47.000000,24.000000,75.000000,75.373120,NaN,12.000000,12.000000,6.000000,6.000000,0.098894,3.000000,41.576310,39.179250,260.000000,260.000000,186.000000,335.000000,33.000000,19.000000,673.000000,11.000000,9.000000,5.000000,5.000000,3.000000,0.000000,0.000000,1.000000,1.000000,10073.000000,10458.000000,10.700000,21.052500,12.400000,8.606667,8.952500,10.873021,21.095475,12.430189,8.618653,8.984906,26472.268550,0.000000,271.000000,219.000000,47.000000,33.000000,0.000000,0.000000,0.000000,0.000000,NaN,55.000000,0.000000,83.000000,10220.500000,1.000000,1.000000,2.000000,2576.000000,3125.000000,925.000000,5986.000000,55218.000000,0.010660,NaN,NaN,NaN,NaN,NaN,3.186000,2.947500,2.584000,47.661441,2.183312
75%,123.000000,109.000000,109.000000,109.542260,NaN,19.000000,18.000000,9.000000,9.000000,0.158565,4.000000,113.999550,114.674660,761.000000,761.000000,460.000000,917.000000,70.750000,55.000000,1827.000000,47.000000,35.000000,14.000000,19.000000,9.000000,1.000000,1.000000,2.000000,4.000000,11014.000000,11150.000000,11.211688,21.503226,12.576623,8.760000,9.271429,11.295855,21.640496,12.673103,8.740000,9.239535,38930.865310,12.500000,742.000000,624.000000,116.000000,70.000000,1.000000,8.000000,0.000000,0.000000,NaN,66.000000,1.000000,103.000000,10891.000000,13.000000,4.000000,15.000000,2916.000000,4858.000000,1552.000000,8683.000000,79920.000000,0.038900,NaN,NaN,NaN,NaN,NaN,3.994000,3.696000,3.258750,48.918435,4.823433
max,23794.000000,33506.000000,8419.000000,8460.883410,NaN,76.000000,112.000000,49.000000,49.000000,1.000000,4.000000,23793.657910,30051.993380,199430.000000,197669.000000,75394.000000,224809.000000,29330.000000,27420.000000,374719.000000,14312.000000,13867.000000,2829.000000,3612.000000,3222.000000,136.000000,630.000000,759.000000,1803.000000,16895.000000,12338.000000,17.731429,26.537143,14.185000,9.742553,10.356579,14.534118,23.685098,13.655098,9.591176,10.131176,261877.286900,100.000000,147350.000000,132153.000000,15980.000000,29330.000000,206.000000,13402.000000,56.000000,14475.000000,NaN,100.000000,417.000000,587.000000,12850.000000,4126.000000,1135.000000,4002.000000,10383.000000,28477.000000,19139.000000,39842.000000,500839.000000,12.351540,NaN,NaN,NaN,NaN,NaN,19.685000,12.885000,12.885000,51.072906,9.529052

Percentage of missing values:
Dynamique Entrepreneuriale                          0.0
Dynamique Entrepreneuriale Service et Commerce      0.0
Synergie Médicale COMMUNE                           0.0
Indice Synergie Médicale                            0.0
SEG Croissance POP                                  0.0
                                                   ...
APL aux médecins généralistes (sans borne d'âge)    0.0
APL aux médecins généralistes de 65 ans et moins    0.0
APL aux médecins généralistes de 62 ans et moins    0.0
latitude                                            0.0
longitude                                           0.0
Length: 75, dtype: float64

In [22]:
insee_csvtest = 'C:\\Users\\alexa\\Downloads\\insee_test.csv'

insee_df.to_csv(insee_csvtest, index=False)

In [23]:
"""
def create_column_types_csv(df, output_file):
    # Créer un DataFrame avec les noms de colonnes et leurs types de données
    column_types_df = pd.DataFrame(df.dtypes).reset_index()
    column_types_df.columns = ['Nom de la colonne', 'Type de données']

    # Compter le nombre de valeurs nulles dans chaque colonne
    null_counts = df.isnull().sum(axis=0).reset_index()
    null_counts.columns = ['Nom de la colonne', 'Nombre de valeurs nulles']

    # Ajouter la première ligne du DataFrame contenant les valeurs des colonnes
    first_row = df.iloc[0].reset_index()
    first_row.columns = ['Nom de la colonne', 'Valeur de la première ligne']

    # Fusionner les DataFrames
    result_df = pd.merge(column_types_df, first_row, on='Nom de la colonne', how='left')
    result_df = pd.merge(result_df, null_counts, on='Nom de la colonne', how='left')

    # Enregistrer le DataFrame dans un fichier CSV
    result_df.to_csv(output_file, index=False)

# Exemple d'utilisation
# Remplacez 'votre_dataframe' par votre DataFrame réel
# et 'chemin/vers/votre/fichier.csv' par le chemin et le nom de fichier souhaités pour le fichier CSV de sortie
create_column_types_csv(insee_df, 'C:\\Users\\alexa\\Downloads\\insee_columns.csv')
"""

"\ndef create_column_types_csv(df, output_file):\n    # Créer un DataFrame avec les noms de colonnes et leurs types de données\n    column_types_df = pd.DataFrame(df.dtypes).reset_index()\n    column_types_df.columns = ['Nom de la colonne', 'Type de données']\n\n    # Compter le nombre de valeurs nulles dans chaque colonne\n    null_counts = df.isnull().sum(axis=0).reset_index()\n    null_counts.columns = ['Nom de la colonne', 'Nombre de valeurs nulles']\n\n    # Ajouter la première ligne du DataFrame contenant les valeurs des colonnes\n    first_row = df.iloc[0].reset_index()\n    first_row.columns = ['Nom de la colonne', 'Valeur de la première ligne']\n\n    # Fusionner les DataFrames\n    result_df = pd.merge(column_types_df, first_row, on='Nom de la colonne', how='left')\n    result_df = pd.merge(result_df, null_counts, on='Nom de la colonne', how='left')\n\n    # Enregistrer le DataFrame dans un fichier CSV\n    result_df.to_csv(output_file, index=False)\n\n# Exemple d'utilisation\n# Remplacez 'votre_dataframe' par votre DataFrame réel\n# et 'chemin/vers/votre/fichier.csv' par le chemin et le nom de fichier souhaités pour le fichier CSV de sortie\ncreate_column_types_csv(insee_df, 'C:\\Users\\alexa\\Downloads\\insee_columns.csv')\n"